# Generated by Django 2.2 on 2020-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen_count',
            field=models.IntegerField(default=0),
        ),
    ]
